package exceptions

class NameAlreadyTaken: Exception()